/** Validation and collaborator failures must preserve coherent published values. */
import {expect,test} from 'vitest';
import {GameSession} from '../../src/engine/session';
import {checkedCounter} from '../../src/engine/progression';
import type {GameCommand,PieceType} from '../../src/engine/types';
import {sequenceFactory} from '../fixtures/piece-sources';
test.each([NaN,Infinity,-Infinity,'10',null,undefined])('nonnumeric/nonfinite elapsed rejected even idle: %s',value=>{let draws=0;const g=new GameSession(()=>()=>{draws++;return 'O';});const before=g.snapshot();expect(()=>g.advance(value as number)).toThrow(TypeError);expect(g.snapshot()).toEqual(before);expect(draws).toBe(0);});
test.each([-1,60000.01])('out of range time %i rejected',n=>expect(()=>new GameSession(sequenceFactory(['O'])).advance(n)).toThrow(RangeError));
test('unknown command rejects outside running without draws',()=>{const g=new GameSession(sequenceFactory(['O']));expect(()=>g.command('hold' as GameCommand)).toThrow(TypeError);expect(g.snapshot().status).toBe('idle');});
test('pause/resume preserve timers and outside-running input is ignored after validation',()=>{const g=new GameSession(sequenceFactory(['O']));g.start();g.advance(18400);g.pause();const before=g.snapshot();g.advance(60000);g.command('left');g.pause();expect(g.snapshot()).toEqual(before);g.resume();g.resume();g.advance(600);expect(g.snapshot().active!.y).toBe(0);});
test('factory/source exceptions and invalid identifiers leave start/restart state unchanged',()=>{let fail=false;const g=new GameSession(()=>{if(fail)throw Error('factory');return()=> 'O';});g.start();g.command('soft-drop');const before=g.snapshot();fail=true;expect(()=>g.restart()).toThrow('factory');expect(g.snapshot()).toEqual(before);const bad=new GameSession(()=>()=> 'bad' as PieceType);expect(()=>bad.start()).toThrow(TypeError);expect(bad.snapshot().status).toBe('idle');let n=0;const second=new GameSession(()=>()=>{if(++n===2)throw Error('second');return 'O';});expect(()=>second.start()).toThrow('second');expect(second.snapshot().active).toBeNull();});
test('failing lock draw publishes no board/counter/piece changes and restart can recover',()=>{let n=0,fail=true;const g=new GameSession(()=>()=>{if(++n===3&&fail)throw Error('source');return 'O';});g.start();g.advance(18999);const before=g.snapshot();expect(()=>g.advance(1)).toThrow('source');const after=g.snapshot();for(const key of ['board','score','lines','level','active','next','status'] as const)expect(after[key]).toEqual(before[key]);fail=false;g.restart();expect(g.snapshot()).toMatchObject({score:0,active:{y:0},grounded:null});});
test('invalid lock source identifier also publishes no partial transition',()=>{let n=0;const g=new GameSession(()=>()=>++n===3?'bad' as PieceType:'O');g.start();g.advance(18999);expect(()=>g.advance(1)).toThrow(TypeError);expect(g.snapshot().board.flat().filter(Boolean)).toHaveLength(0);});
test('maximum advance matches subdivisions and fractional timing stays within tolerance',()=>{const a=new GameSession(sequenceFactory(['O'])),b=new GameSession(sequenceFactory(['O']));a.start();b.start();a.advance(60000);for(let i=0;i<6;i++)b.advance(10000);expect(a.snapshot()).toEqual(b.snapshot());a.restart();b.restart();a.advance(18345.6789);for(const n of [10000.1234,8345.5555])b.advance(n);const x=a.snapshot(),y=b.snapshot();expect(x.active).toEqual(y.active);expect(x.board).toEqual(y.board);expect(Math.abs(x.gravityElapsedMs-y.gravityElapsedMs)).toBeLessThan(1e-6);expect(Math.abs(x.grounded!.elapsedMs-y.grounded!.elapsedMs)).toBeLessThan(1e-6);});
test('exact nonnegative safe-integer counter guard rejects overflow before publication',()=>{expect(checkedCounter(Number.MAX_SAFE_INTEGER)).toBe(Number.MAX_SAFE_INTEGER);for(const n of [Number.MAX_SAFE_INTEGER+1,-1,0.5,Infinity])expect(()=>checkedCounter(n)).toThrow(RangeError);});
